id: I8C55CF16
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:37:09+00:00'
last_modified: '2022-06-07T17:43:22.773546+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14557
  title: གསུང་འབུམ། ཆོས་ཀྱི་དབང་ཕྱུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    06A9:
      image_group_id: I1KG14559
      title: ''
      total_pages: 946
      order: 1
      base_file: 06A9.txt
    405D:
      image_group_id: I1KG14560
      title: ''
      total_pages: 926
      order: 2
      base_file: 405D.txt
    51C9:
      image_group_id: I1KG14561
      title: ''
      total_pages: 712
      order: 3
      base_file: 51C9.txt
    06B0:
      image_group_id: I1KG14562
      title: ''
      total_pages: 746
      order: 4
      base_file: 06B0.txt
    ADFF:
      image_group_id: I1KG14563
      title: ''
      total_pages: 752
      order: 5
      base_file: ADFF.txt
    D659:
      image_group_id: I1KG14564
      title: ''
      total_pages: 746
      order: 6
      base_file: D659.txt
    68C7:
      image_group_id: I1KG14565
      title: ''
      total_pages: 728
      order: 7
      base_file: 68C7.txt
    '4146':
      image_group_id: I1KG14566
      title: ''
      total_pages: 804
      order: 8
      base_file: 4146.txt
    E3ED:
      image_group_id: I1KG14567
      title: ''
      total_pages: 750
      order: 9
      base_file: E3ED.txt
    4E73:
      image_group_id: I1KG14568
      title: ''
      total_pages: 770
      order: 10
      base_file: 4E73.txt
    EFEE:
      image_group_id: I1KG14569
      title: ''
      total_pages: 876
      order: 11
      base_file: EFEE.txt
    04A2:
      image_group_id: I1KG14570
      title: ''
      total_pages: 882
      order: 12
      base_file: 04A2.txt
    3AB8:
      image_group_id: I1KG14571
      title: ''
      total_pages: 828
      order: 13
      base_file: 3AB8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
