id: I8C55CF16
legacy_id: P003119
ocr_import_info:
  bdrc_scan_id: W1KG14557
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T22:29:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:58:35.686081+00:00'
last_modified: 2022-08-31 15:02:15.353962
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG14557
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG14557
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཆོས་ཀྱི་དབང་ཕྱུག
  author: བྲག་དཀར་རྟ་སོ་སྤྲུལ་སྐུ་ཆོས་ཀྱི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.9178633587879831
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG14564:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14564
      total_pages: 746
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG14564.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.92277913222241
    legacy_id: v006
  I1KG14567:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14567
      total_pages: 750
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG14567.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8981833861487357
    legacy_id: v009
  I1KG14566:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14566
      total_pages: 804
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG14566.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.910436803239189
    legacy_id: v008
  I1KG14561:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14561
      total_pages: 712
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG14561.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9240721777486927
    legacy_id: v003
  I1KG14569:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14569
      total_pages: 876
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG14569.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.92016401083379
    legacy_id: v011
  I1KG14571:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14571
      total_pages: 828
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG14571.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9202261726859681
    legacy_id: v013
  I1KG14563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14563
      total_pages: 752
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG14563.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9186671702707179
    legacy_id: v005
  I1KG14560:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14560
      total_pages: 926
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG14560.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9264494015402138
    legacy_id: v002
  I1KG14562:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14562
      total_pages: 746
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG14562.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9171895840844253
    legacy_id: v004
  I1KG14565:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14565
      total_pages: 728
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG14565.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9157328294943217
    legacy_id: v007
  I1KG14568:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14568
      total_pages: 770
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG14568.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9158592937894209
    legacy_id: v010
  I1KG14570:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14570
      total_pages: 882
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG14570.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9162544054552012
    legacy_id: v012
  I1KG14559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG14559
      total_pages: 946
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG14559.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9198841896403672
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
