id: P003119
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14557
  title: གསུང་འབུམ། ཆོས་ཀྱི་དབང་ཕྱུག
  author: ''
  volumes:
    b9777f12432a4ef98928aec57a0fcfa3:
      image_group_id: I1KG14559
      title: ''
      volume_number: 1
      total_pages: 946
    9090f83708f641baa55285276c858a17:
      image_group_id: I1KG14560
      title: ''
      volume_number: 2
      total_pages: 926
    f8bcf1c37dc549c1bfdb15bde132f797:
      image_group_id: I1KG14561
      title: ''
      volume_number: 3
      total_pages: 712
    e5cece261f5443f199bbcbac05fe818d:
      image_group_id: I1KG14562
      title: ''
      volume_number: 4
      total_pages: 746
    bec94ecc52ca42b08802c3e92e49001c:
      image_group_id: I1KG14563
      title: ''
      volume_number: 5
      total_pages: 752
    a3406b5a9441438eaf541503aab58e26:
      image_group_id: I1KG14564
      title: ''
      volume_number: 6
      total_pages: 746
    f6a307d90491499eb9562e5e7a7dd897:
      image_group_id: I1KG14565
      title: ''
      volume_number: 7
      total_pages: 728
    942137882c1b46f29a12ba9020b47cd9:
      image_group_id: I1KG14566
      title: ''
      volume_number: 8
      total_pages: 804
    8dbc99dd920f403bb75565c508fb2c89:
      image_group_id: I1KG14567
      title: ''
      volume_number: 9
      total_pages: 750
    1674763195bf456e80210f8d339e1088:
      image_group_id: I1KG14568
      title: ''
      volume_number: 10
      total_pages: 770
    943f77c8b3964b46960a508a7529a775:
      image_group_id: I1KG14569
      title: ''
      volume_number: 11
      total_pages: 876
    bfa3c52160f9454f9e880a4ec6e82199:
      image_group_id: I1KG14570
      title: ''
      volume_number: 12
      total_pages: 882
    f0c767edc8034032a7c02e4523ea5960:
      image_group_id: I1KG14571
      title: ''
      volume_number: 13
      total_pages: 828
